#
# Stating common version definitions.
#
set(SOKKETTER_VERSION_MAJOR 1)
set(SOKKETTER_VERSION_MINOR 0)
set(SOKKETTER_VERSION_MICRO 0)
set(SOKKETTER_VERSION_NANO 0)
set(SOKKETTER_VERSION_SHA "0")

#
# Reading Git SHA value.
#
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
                    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
                    RESULT_VARIABLE GIT_CALL_RESULT
                    OUTPUT_VARIABLE SOKKETTER_VERSION_SHA
                    OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT GIT_CALL_RESULT EQUAL "0")
        message(FATAL_ERROR "\"${GIT_EXECUTABLE} rev-parse --short HEAD\"¨ failed with ${GIT_CALL_RESULT}")
    endif()
else()
    message(FATAL_ERROR "Git executable is not found, please install it.")
endif()

#
# Passing definitions into project sources.
#
add_definitions(-DSOKKETTER_VERSION_MAJOR=${SOKKETTER_VERSION_MAJOR} -DSOKKETTER_VERSION_MINOR=${SOKKETTER_VERSION_MINOR} -DSOKKETTER_VERSION_MICRO=${SOKKETTER_VERSION_MICRO} -DSOKKETTER_VERSION_NANO=${SOKKETTER_VERSION_NANO} -DSOKKETTER_VERSION_SHA="${SOKKETTER_VERSION_SHA}")

message("Project version: ${SOKKETTER_VERSION_MAJOR}.${SOKKETTER_VERSION_MINOR}.${SOKKETTER_VERSION_MICRO}.${SOKKETTER_VERSION_NANO}.${SOKKETTER_VERSION_SHA}")

message("")
