name: CMake (compile and test)

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-only:
    runs-on: ${{ matrix.os }}
    env:
      path-separator: ${{ (startsWith(matrix.os, 'windows') && '\') || '/' }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13, macos-14]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}${{ env.path-separator }}build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies (Ubuntu only)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        sudo apt update
        sudo apt install libfuse2 gcc lcov libudev-dev ninja-build -y

    - name: Install dependencies (MacOS only)
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: |
        brew install lcov

    - name: Install Qt6 dependencies
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.*'

    - name: Run Python build script
      run: python -m Build

    - name: Run tests
      run: |
        ctest --output-on-failure --test-dir ${{ steps.strings.outputs.build-output-dir }}
